# Generated by Django 3.2.9 on 2021-12-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
                ('last_post', models.DateField()),
                ('post_periodicity', models.IntegerField()),
                ('update_periodicity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('pollution_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allowable_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chronology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chronology')),
            ],
        ),
    ]
